name: weather_riverpod_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  freezed: ^3.1.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  go_router: ^16.0.0
  recase: ^4.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading.gif
    - assets/images/no_image_icon.png
    - env/.env
